ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /


utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

EcommerceRoutes:
    resource: "@EcommerceBundle/Controller"
    type:     annotation
