<?php

namespace Ecommerce\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends EntityRepository
{
    public function getProduitsbyCategorie($id)
    {
        $qd = $this->createQueryBuilder('u')
                   ->select('u')
                   ->where('u.categorie = :categorie')
                    ->orderBy('u.id')
                    ->setParameter('categorie', $id);
        return $qd->getQuery()->getResult();
    }
}
